name: owlbot_example
description: Example app to showcase how to use owlbot_dart package
version: 0.0.1
homepage: https://github.com/lohanidamodar/owlbot_dart
publish_to: none

environment: 
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  owlbot_dart:
    path: ..

