name: owlbot_dart
description: A new Flutter package project.
version: 1.0.0
author: Damodar Lohani
homepage: https://github.com/lohanidamodar/owlbot_dart

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter: null
