name: owlbot_dart
description: A clean and simple interface to interact with owlbot.info, dictionary API. Returns response in nice formatted dart objects
version: 1.0.3
homepage: https://dlohani.com.np
repository: https://github.com/lohanidamodar/owlbot_dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2
  meta: ^1.2.2

dev_dependencies:
  ? test

